name: Generate Index Webpage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # Add this permissions block
    permissions:
      contents: write

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Generate index.html
      run: |
        # Start the HTML file with a header and some CSS for styling
        echo '<!DOCTYPE html>' > index.html
        echo '<html lang="en">' >> index.html
        echo '<head>' >> index.html
        echo '  <meta charset="UTF-8">' >> index.html
        echo '  <meta name="viewport" content="width=device-width, initial-scale=1.0">' >> index.html
        echo '  <title>Page Index</title>' >> index.html
        echo '  <style>' >> index.html
        echo '    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 2rem auto; padding: 0 1rem; }' >> index.html
        echo '    h1 { color: #111; border-bottom: 2px solid #f0f0f0; padding-bottom: 0.5rem; }' >> index.html
        echo '    ul { list-style-type: none; padding: 0; }' >> index.html
        echo '    li { margin: 0.75rem 0; }' >> index.html
        echo '    a { text-decoration: none; color: #007bff; font-size: 1.1rem; transition: color 0.2s; }' >> index.html
        echo '    a:hover { color: #0056b3; text-decoration: underline; }' >> index.html
        echo '    footer { margin-top: 3rem; text-align: center; font-size: 0.8rem; color: #777; }' >> index.html
        echo '  </style>' >> index.html
        echo '</head>' >> index.html
        echo '<body>' >> index.html
        echo '  <h1>Index of Pages</h1>' >> index.html
        echo '  <p>Welcome! Here is a list of all available pages on this site.</p>' >> index.html
        echo '  <ul>' >> index.html

        # Find all HTML files (excluding index.html itself), format the name, and add it to a list
        for file in $(find . -maxdepth 1 -name "*.html" -o -name "*.htm"); do
          filename=$(basename "$file")
          if [ "$filename" != "index.html" ]; then
            pagename=$(echo "$filename" | sed 's/\.[^.]*$//' | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)} 1')
            echo "    <li><a href=\"$filename\">$pagename</a></li>" >> index.html
          fi
        done

        # Close the HTML tags
        echo '  </ul>' >> index.html
        echo '  <footer><p><em>This page is automatically generated and updated by a GitHub Action.</em></p></footer>' >> index.html
        echo '</body>' >> index.html
        echo '</html>' >> index.html

    - name: Commit and push if changed
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "docs: update index.html"
        file_pattern: index.html
