name: Generate Index Webpage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Generate index.html
      run: |
        # Start the HTML file with updated title and a more delicate CSS style
        echo '<!DOCTYPE html>' > index.html
        echo '<html lang="en">' >> index.html
        echo '<head>' >> index.html
        echo '  <meta charset="UTF-8">' >> index.html
        echo '  <meta name="viewport" content="width=device-width, initial-scale=1.0">' >> index.html
        echo '  <title>matthewf01 Github Coding Projects</title>' >> index.html
        echo '  <style>' >> index.html
        echo '    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; line-height: 1.6; color: #343a40; max-width: 900px; margin: 0 auto; padding: 2rem; background: linear-gradient(to bottom, #f8f9fa, #ffffff); min-height: 100vh; }' >> index.html
        echo '    h1 { color: #212529; border-bottom: 2px solid #e9ecef; padding-bottom: 0.5rem; text-align: center; }' >> index.html
        echo '    h2 { font-size: 1.2rem; margin-top: 2.5rem; color: #495057; border-left: 3px solid #ced4da; padding-left: 0.75rem; width: 100%; }' >> index.html
        echo '    ul { list-style-type: none; padding: 0; display: flex; flex-wrap: wrap; gap: 15px; margin-top: 1rem; }' >> index.html
        echo '    li { margin: 0; }' >> index.html
        echo '    a { display: inline-block; text-decoration: none; background-color: #ffffff; color: #495057; padding: 12px 18px; border: 1px solid #dee2e6; border-radius: 8px; font-size: 1rem; font-weight: 500; box-shadow: 0 1px 3px rgba(0,0,0,0.05); transition: all 0.2s ease-in-out; }' >> index.html
        echo '    a:hover { color: #007bff; border-color: #007bff; box-shadow: 0 4px 10px rgba(0,0,0,0.1); transform: translateY(-2px); }' >> index.html
        echo '    footer { margin-top: 3rem; text-align: center; font-size: 0.8rem; color: #adb5bd; }' >> index.html
        echo '  </style>' >> index.html
        echo '</head>' >> index.html
        echo '<body>' >> index.html
        echo '  <h1>matthewf01 Github Coding Projects</h1>' >> index.html

        # Function to process files in a given directory
        process_directory() {
            local dir_path=$1
            local file_list=$(find "$dir_path" -maxdepth 1 -name "*.html" -o -name "*.htm" | sort)
            if [ -n "$file_list" ]; then
                echo '  <ul>' >> index.html
                for file in $file_list; do
                    filename=$(basename "$file")
                    page_title=""

                    # Read the entire file content, remove newlines, and then search
                    file_content=$(cat "$file" | tr -d '\r\n')

                    # 1. Try to get title from the first <h1> tag (case-insensitive)
                    page_title=$(echo "$file_content" | grep -i -m 1 -oP '(?<=<h1[^>]*>).*(?=</h1>)')
                    
                    # 2. If no <h1>, try to get title from the <title> tag (case-insensitive)
                    if [ -z "$page_title" ]; then
                        page_title=$(echo "$file_content" | grep -i -m 1 -oP '(?<=<title[^>]*>).*(?=</title>)')
                    fi
                    
                    # 3. If still no title, fall back to the formatted filename
                    if [ -z "$page_title" ]; then
                        page_title=$(echo "$filename" | sed 's/\.[^.]*$//' | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)} 1')
                    fi

                    if [ "$filename" != "index.html" ]; then
                        echo "    <li><a href=\"$file\">$page_title</a></li>" >> index.html
                    fi
                done
                echo '  </ul>' >> index.html
            fi
        }

        # Process root directory
        echo "<h2>Root</h2>" >> index.html
        process_directory "."

        # Process subdirectories
        for dir in $(find . -mindepth 1 -type d -not -path './.git*' -not -path './.github*'); do
            dir_name_formatted=$(echo "$dir" | sed 's|^\./||' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)} 1')
            echo "<h2>$dir_name_formatted</h2>" >> index.html
            process_directory "$dir"
        done

        # Close the HTML tags
        echo '  <footer><p><em>This page is automatically generated and updated by a GitHub Action.</em></p></footer>' >> index.html
        echo '</body>' >> index.html
        echo '</html>'
        
    - name: Commit and push if changed
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "docs: update index.html with robust h1/title logic"
        file_pattern: index.html
